/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "% Chart": "% 图表",
    "All question and additional information about the game will be collected here. Currently there is no Information, i will add this based on the feedback.": "有关游戏的所有问题和其他信息都将在此处收集。 目前没有信息，我将根据反馈添加此信息。",
    "Buy": "购买",
    "Close": "关闭",
    "Change": "盈亏",
    "Example Info": "示例信息",
    "Help and FAQ": "帮助 和 FAQ",
    "I thought maybe others will enjoy this too, so i decided to push it to the world.": "我想也许其他人也会喜欢这个，所以我决定把它推向世界。",
    "Let's start with Stonk Idle": "让我们从 股市放置 开始",
    "Ok": "好的",
    "Or you can": "或者你可以",
    "Popup": "弹框",
    "Sell": "出售",
    "Skip Tutorial?": "跳过教程？",
    "Store in Savings Account": "存入储蓄账户",
    "This is a little side project i started in my vacation. I like this type of idle games and developed it in the beginning just for me.": "这是我在假期开始的一个小项目。 我喜欢这种类型的放置游戏，并在一开始就为我开发了它。",
    "This is a Stock-Market idle Simulator!": "这是一个股市放置模拟器！",
    "This tutorial will help you to understand the UI and the basic game mechanics!": "本教程将帮助您了解 UI 和基本游戏机制！",
    "Welcome to the Game!": "欢迎来到游戏！",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "Accounts": "账户",
    "Age": "年龄",
    "Balance": "余额",
    "Cicle": "循环",
    "Credit Account": "信用账户",
    "Get Credit": "贷款",
    "here you can lend money!": "在这里你可以借钱！",
    "here you find Information about the Market and your Accounts!": "在这里您可以找到有关市场和您的账户的信息！",
    "here you store your Money for your retirement. This is your Game-Score and also you can get interest from it! You can store money there but not withdraw!": "在这里，您可以存放您的退休金。 这是您的游戏分数，您也可以从中获得兴趣！ 你可以在那里存钱，但不能取款！",
    "I have added a own Time-System for easier calculation and modification. Every 100 Ticks a new Period starts! Most updates happen after one Period": "我添加了一个自己的时间系统，以便于计算和修改。 每 100 个刻度，一个新的周期开始！ 大多数更新发生在一个时期之后",
    "Interst": "利息",
    "Main Account": "主账户",
    "Meta - Information": "元信息",
    "Next to the Time we have your Accounts": "在我们拥有您的帐户的时间旁边",
    "Pay Credit": "还款",
    "Pay/Sell/Store": "支付/销售/存储",
    "Period": "周期",
    "Periods": "周期",
    "Savings": "储蓄",
    "Savings Account": "储蓄账户",
    "Ticks": "Tick",
    "Time": "时间",
    "Top": "最佳",
    "with this you buy your Stocks and Items in the Store": "用这个你在商店里买你的股票和物品",
    "you use the buttons next to the Accounts to transfere money to or from!": "您可以使用帐户旁边的按钮进行转入或转出！",
    "Account": "帐户",
    "All the other Features": "所有其他功能",
    "Bottom": "底部",
    "Buy / Sell": "买卖",
    "Buy in the Store": "在商店购买",
    "Earn money with Interest": "用利息赚钱",
    "Game": "游戏",
    "General": "一般的",
    "Goals": "目标",
    "Have in Saving Account": "有储蓄账户",
    "Here you can Buy and Sell shares": "在这里您可以买卖股票",
    "here you can Reset your Save or restart the Tutorial. There are also a Discord link, in case you want to get in contact with the developer!": "在这里您可以重置您的保存或重新启动教程。如果您想与开发人员联系，还有一个 Discord 链接！",
    "Here you can see all avaliable Business you can buy Stocks from. You start with 3 Business but there will be more later!": "在这里，您可以查看可以从中购买股票的所有可用业务。您从 3 商业 开始，但以后会有更多！",
    "here you can unlock more features and information. Each Class needs a specific time (Periods) and cost per Period": "在这里您可以解锁更多功能和信息。每个班级需要特定的时间（时期）和每个时期的成本",
    "Here you find more information about the Prices of the Shares": "在这里您可以找到有关股票价格的更多信息",
    "here you find the current prices and the change since the last period, also the Name of the selected stock": "在这里您可以找到当前价格和自上一时期以来的变化，以及所选股票的名称",
    "Here you will find the Chart for the Stonk and current information.": "在这里，您将找到 股市 图表和当前信息。",
    "In the last section you can find News and Logs": "在最后一部分中，您可以找到新闻和日志",
    "In this bottom section you can find all the other Features, some of them have to be unlocked!": "在此底部，您可以找到所有其他功能，其中一些必须解锁！",
    "Information about the Business / Shares. You start with minimal information but can get more later!": "有关业务/股份的信息。您从最少的信息开始，但以后可以获得更多信息！",
    "Left": "剩下",
    "List of all Business": "所有业务列表",
    "Logs": "日志",
    "Market News": "市场新闻",
    "More detail": "更多详情",
    "More Information": "更多信息",
    "Name of the Business": "企业名称",
    "News": "消息",
    "News and Logs": "新闻和日志",
    "Owned Stocks, Increase of your Depot": "自有库存，增加您的仓库",
    "Please get a News-Subscription to read the latest News!": "请获取新闻订阅以阅读最新新闻！",
    "Prices": "价格",
    "Right": "正确",
    "School": "学校",
    "Sell the Shares!": "卖出股票！",
    "Shares": "股份",
    "So far this is the end of the Tutorial. Have fun!": "至此教程结束。玩得开心！",
    "Subscription for": "订阅",
    "The Chart": "图表",
    "There can be a lot more information be unlocked": "可以解锁更多信息",
    "they show you what's happening in the Game. Goals Reached, Interest, Tax, etc...": "他们向您展示了游戏中正在发生的事情。达到的目标，利息，税收等...",
    "this are your goals for the game. Every time you achive a goal, you get a small bonus!": "这是你的游戏目标。每次完成一个目标，您都会获得一笔小额奖金！",
    "this showes you the development of the Stock over the last 50 periods": "这向您展示了过去 50 个时期的股票发展情况",
    "Top of the Chart": "图表顶部",
    "Value of your Stocks": "您的股票价值",
    "Where are the Stonks!": "股市在哪里！",
    "you can buy a News-Subsciption in the Store. They show you relevant Market-Information": "您可以在商店中购买新闻订阅。他们向您展示相关的市场信息",
    "Your Depot": "您的仓库",
    "A Shop": "一个商店",
    "Contact": "联系",
    "Game Version": "游戏版本",
    "Last Update": "最后更新",
    "Learn": "学习",
    "LOL": "LOL",
    "per Period": "每个时期",
    "Periods a": "周期 a",
    "Reset Save": "重置保存",
    "RESET THE SAFE": "重置保险箱",
    "Reset the Save?": "重置保存？",
    "Restart Tutorial": "重启教程",
    "Where the Money goes": "钱去哪儿了",
    "You get access to the Shop!": "您可以访问商店！",
    "You get access to your balance sheet!": "您可以访问您的资产负债表！",
    "Stop": "停止",
    "Stop School": "停止课程",
    "When you stop the class you lose all your progress!": "当您停止课程时，您将失去所有进度！",
    "Shares to": "股的",
    "Stopped School!": "已停止课程!",
    "Total": "总计",
    "What is it wroth?": "它有什么价值？",
    "You discover another Bussines to invest in!": "您发现另一个可以投资的业务！",
    "You finished Shool!": "你完成学业了！",
    "You learn to calculate the whole Portfolio value": "你将学会计算整个投资组合价值",
    "Change of Cicle": "改变循环",
    "Draw a ticket for a price": "抽一张有价票",
    "Get your latest Market news!": "获取您的最新市场新闻！",
    "JackPot!": "大奖！",
    "News Subscription": "新闻订阅",
    "Time left": "剩余时间",
    "Goal reached! Get 1% discount on Store Items": "目标达成！ 获得商店商品 1% 的折扣",
    "Happy new Cicle": "新循环快乐",
    "We now start the Cicle 1! \n We wish you luck with your Trades!": "我们现在开始第 1 周期！ \n 我们祝您交易顺利！",
    "Nothing to buy right now. More goods are on the way!": "现在没什么可买的。 更多商品正在路上！",
    "- Price per Share": "- 每股价格",
    "Interest period extension": "利息期延长",
    "Learn how to read to Performance of the Business to determine the Chart": "了解如何阅读业务绩效以确定图表",
    "More knowledge about the Stonk!": "更多关于股市的知识！",
    "Where are they going?": "他们要去哪里？",
    "You learn more information about your Depot": "您了解有关您的仓库的更多信息",
    "Get additional historical information about the Stock!": "获取有关股票的更多历史信息！",
    "More numbers for your life!": "为您的生活提供更多数字！",
    "What was in the Past": "过去发生了什么",
    "You get access to additional Numbers": "您可以访问其他号码",
    "Buy Shares": "购买股份",
    "Sell Shares": "出售股份",
    "Interest": "利息",
    "Store / School": "库存 / 学习",
    "Not enough fundings to pay for School!": "没有足够的资金来支付学校的费用！",
    "Buy In": "买入",
    "Diff": "盈亏",
    "per Share": "每股",
    "Understand the Market": "了解市场",
    "Understand the Market Movement": "了解市场动向",
    "You learn to know how the Market volatility is!": "您将学会了解市场的波动性！",
    "You understand the Performance of the whole Market": "您将了解整个市场的表现",
    "Goal reached! Get 190 to your Saving Interest-period": "目标达成!给你的储蓄存款期加190",
    "Performance": "表现",
    "Buy Amount": "购买金额",
    "Buy Quantity": "购买数量",
    "Buy/Sell Spread": "买入/卖出 差价",
    "Chance Item in Store": "商店中的物品几率",
    "Discount in Store": "店内折扣",
    "Game Stats": "游戏统计",
    "Item Quantity": "物品数量",
    "Items amount": "物品金额",
    "Max Item in Store": "商店中的最大物品",
    "Meta": "元",
    "Sell Amount": "出售金额",
    "Sell Quantity": "出售数量",
    "TAX": "税",
    "TAX Percentage": "税率",
    "Time per Period": "每期时间",
    "High": "高",
    "Medium": "中",
    "Low": "低",
    "VeryHigh": "很高",
    "VeryLow": "很低",
    "End": "结尾",
    "Info Age": "信息时代",
    "Info Cicle": "信息循环",
    "Market Potential": "市场潜力",
    "Market Potential!": "市场潜力！",
    "Market Volatility!": "市场波动！",
    "Since": "自从",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "WIP": "WIP",
    "UWU": "UWU",
    "Tax": "税",
    "ARE": "ARE",
    "EBT": "EBT",
    "Started School: More numbers for your life!": "开始学习：为您的生活提供更多数字！",
    "Started School: More knowledge about the Stonk!": "开始学习：更多关于股市的知识！",
    "Started School: Where the Money goes": "开始学习：钱去哪儿了",
    "Started School: A Shop": "开始学习：商店",
    "Started School: What is it wroth?": "开始学习：值多少钱？",
    "Nerd Errors Games": "阳光后援团",
    "World Idle Platform": "世界放置平台",
    "Ultra Waifu United": "锅巴汉化",
    "Little Lama Loft": "Git游戏",
    "Riddle with me": "摸鱼公司",
    "Alter Reconstruction": "放置军团",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Saving Account Interest Periods ": "储蓄账户利息期 ",
    "Saving Account Interest-Rate ": "储蓄账户利率 ",
    "Lower Shop prices by: ": "降低店铺价格：",
    "Bought LOL -": "购买 LOL -",
    "Bought RWM -": "购买 RWM -",
    "Bought WIP -": "购买 WIP -",
    "Bought ARE -": "购买 ARE -",
    "Bought UWU -": "购买 UWU -",
    "Whats in the Market ": "有什么在市场 ",
    "Soled ": "出售 ",
    "Store: Item JackPot! was bought for ": "商店： 物品大奖！ 购买花费 ",
    "Store: Item News Subscription was bought for ": "商店：物品新闻订阅被购买",
    "Your periods for your Savings interest get extended by: ": "您的储蓄利息期限通过以下方式延长：",
    "Increase max Items in the Shop by: ": "通过以下方式增加商店中的最大物品上限：",
    "Started School: Whats in the Market ": "开始学习：市场上有什么",
    "Credit: ": "贷款: ",
    "Savings: ": "节省：",
    "Alter Reconstruction got an update in it's potential. \n Potential is now: ": "放置军团 的潜力得到了更新。 \n潜力现在是：",
    "Little Lama Loft got an update in it's potential. \n Potential is now: ": "Git游戏 的潜力得到了更新。 \n潜力现在是：",
    "Evaluation of the Market Potential got an update! \n Potential is now: ": "市场潜力评估更新！ \n 潜力现在是：",
    "Potential: ": "潜力：",
    "The Market volatility changed. It is now: ": "市场波动发生了变化。 现在：",
    "Ultra Waifu United got an update in it's potential. \n Potential is now: ": "世界放置平台 的潜力得到了更新。 \n潜力现在是：",
    "World Idle Platform got an update in it's potential. \n Potential is now: ": "锅巴汉化 的潜力得到了更新。 \n潜力现在是：",
    "Credit Account Interest-Rate ": "信用账户利率 ",
    "Chance for Items added to the Shop: ": "物品添加到商店的几率：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)€$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)€$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)€$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Main: (.+)€$/, '主要：$1€'],
    [/^Main: (.+) Reason: interest payment$/, '主要：$1 原因：利息支付'],
    [/^Main: (.+) Reason: Tax Return$/, '主要：$1 原因：退税'],
    [/^Main: (.+) Reason: interest income$/, '主要：$1 原因：利息收入'],
    [/^Main: (.+) Reason: Pay Taxes$/, '主要：$1 原因：纳税'],
    [/^Main: (.+) Reason: School Fee$/, '主要：$1 原因：学费'],
    [/^Not enough shares owned to sell (.+) \((.+) owned$/, '拥有的股份不足以出售 $1（拥有 $2'],
    [/^Not enough funding to buy (.+) \((.+) needed$/, '没有足够的资金购买 $1（需要 $2'],
    [/^Not enough free stocks to buy (.+) \((.+) avaliable$/, '没有足够的空闲股票可以购买 $1（$2 可用'],
    [/^News Subscription was bought for (.+) Periods$/, '新闻订阅已购买 $1 期'],
    [/^You got a (.+). Beat (.+) to win!$/, '你得到了 $1。超过 $2 以获胜！'],
    [/^Goal reached! Get (.+) to your Saving Interest-period$/, '目标达成！ 获得 $1 的储蓄利息期'],
    [/^Goal reached! Get (.+) to your Saving Interest-rate$/, '目标达成！ 获得 $1 的储蓄利率'],
    [/^Goal reached! Get (.+) to your Credit Interest-rate$/, '目标达成！ 获得 $1 的信用利率'],
    [/^Goal reached! Get (.+) discount on Store Items$/, '目标达成！ 获得商店商品 $1 的折扣'],
    [/^We now start the Cicle (.+)! \n We wish you luck with your Trades!$/, '我们现在开始第 $1 周期！ \n 我们祝您交易顺利！'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Offline for: (.+) Days or (.+) Hours or (.+) Minutes. You got offline Earnings!$/, '离线时间：$1 天 $2 小时 $3 分钟。 您获得了离线收入！'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) sec$/, '$1 秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);